services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"    # Consul UI and API port
      - "8600:8600/udp" # DNS interface for service discovery
      - "8300:8300"    # RPC server
      - "8301:8301/tcp"
      - "8301:8301/udp"
      - "8302:8302/tcp"
      - "8302:8302/udp"
    command: agent -server -ui -bootstrap-expected=1 -client=0.0.0.0 
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:

        - ./consul-config:/consul/config
